# Assignment - 3

# Task 1 - 1

In [1]:
def divide():
    return 5/0

In [2]:
try :
    divide()
except ZeroDivisionError:
    print("exception caught!.. division by zero..")
except Exception as e:
    print(e)
finally:
    print("This is successfully executed!!")

exception caught!.. division by zero..
This is successfully executed!!


# Task 1 - 2

In [3]:
subjects=["Americans ","Indians"]
verbs=["play","watch"]
objects=["Baseball","Cricket"]

In [4]:
for i in subjects:
    for j in verbs:
        for k in objects:
            print(i + " " + j + " " + k)

Americans  play Baseball
Americans  play Cricket
Americans  watch Baseball
Americans  watch Cricket
Indians play Baseball
Indians play Cricket
Indians watch Baseball
Indians watch Cricket


# Task 2 - 1

In [7]:
def raisedtopower(l,n,increasing):
    f = []
    for i in l:
        x = []
        for j in range(n):
            x.append(i**j)
        if increasing == True:
            f.append(x)
        else :
            f.append(x[::-1])
    return f

In [8]:
l = [2,3,4,6]

In [9]:
ans = raisedtopower(l,5,True)

In [10]:
ans

[[1, 2, 4, 8, 16],
 [1, 3, 9, 27, 81],
 [1, 4, 16, 64, 256],
 [1, 6, 36, 216, 1296]]

In [12]:
import numpy as np

In [13]:
l = np.array([1, 2, 3, 5])

In [14]:
np.vander(l,5)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [625, 125,  25,   5,   1]])

In [15]:
np.vander(l,5,increasing=True)

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   5,  25, 125, 625]])

In [16]:
np.vander(l,increasing=True)

array([[  1,   1,   1,   1],
       [  1,   2,   4,   8],
       [  1,   3,   9,  27],
       [  1,   5,  25, 125]])